export const RECORD_SNAPSHOT = "RECORD_SNAPSHOT";
export const SET_DEBUG_MODE = "SET_DEBUG_MODE";
export const DOMAIN_NOT_ALLOWED = "DOMAIN_NOT_ALLOWED";
export const BOOTSTRAP_DONE = "BOOTSTRAP_DONE";
export const INIT_IFRAME = "INIT_IFRAME";
export const TRACK = "TRACK";
export const PUSH_EVENT = "PUSH_EVENT";
