export const SET_DEBUG_MODE = "SET_DEBUG_MODE";
export const DOMAIN_NOT_ALLOWED = "DOMAIN_NOT_ALLOWED";
export const BOOTSTRAP_DONE = "BOOTSTRAP_DONE";
export const INIT_IFRAME = "INIT_IFRAME";
export const ERROR = "ERROR";
export const CHANGE_CONTAINER_CLASS = 'CHANGE_CONTAINER_CLASS';
export const CHANGE_CONTAINER_CLASS_DONE = 'CHANGE_CONTAINER_CLASS_DONE';
export const START_FEEDBACK_FLOW = 'START_FEEDBACK_FLOW';